version: "3.7"

services:

  flask:
    build: ./Container-flask
    container_name: flask
    restart: always
    environment:
      - APP_NAME=MyFlaskApp
    

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "90:90"